const categories = [
  { id: 'trees', name: 'Trees', icon: '🌳', description: 'Learn about trees, forests, and their importance', order: 1, totalLessons: 30, color: '#4CAF50' },
  { id: 'water', name: 'Water', icon: '💧', description: 'Discover water, oceans, rivers, and conservation', order: 2, totalLessons: 30, color: '#2196F3' },
  { id: 'earth', name: 'Earth', icon: '🌍', description: 'Explore our planet, mountains, soil, and rocks', order: 3, totalLessons: 30, color: '#795548' },
  { id: 'recycling', name: 'Recycling', icon: '♻️', description: 'Learn to reduce, reuse, and recycle waste', order: 4, totalLessons: 30, color: '#9C27B0' },
  { id: 'animals', name: 'Animals', icon: '🐯', description: 'Discover wildlife, pets, and animal habitats', order: 5, totalLessons: 30, color: '#FF9800' },
  { id: 'energy', name: 'Energy', icon: '⚡', description: 'Explore renewable and non-renewable energy', order: 6, totalLessons: 30, color: '#FFEB3B' },
  { id: 'oceans', name: 'Oceans', icon: '🌊', description: 'Dive into marine life and ocean ecosystems', order: 7, totalLessons: 30, color: '#00BCD4' },
  { id: 'plants', name: 'Plants', icon: '🌱', description: 'Study plant life, growth, and photosynthesis', order: 8, totalLessons: 30, color: '#8BC34A' },
  { id: 'forests', name: 'Forests', icon: '🏞️', description: 'Explore forest ecosystems and biodiversity', order: 9, totalLessons: 30, color: '#2E7D32' },
  { id: 'wildlife', name: 'Wildlife', icon: '🦁', description: 'Learn about wild animals and their protection', order: 10, totalLessons: 30, color: '#E65100' },
  { id: 'climate', name: 'Climate', icon: '🌤️', description: 'Understand climate change and weather patterns', order: 11, totalLessons: 30, color: '#607D8B' },
  { id: 'weather', name: 'Weather', icon: '⛅', description: 'Learn about rain, wind, storms, and seasons', order: 12, totalLessons: 30, color: '#90CAF9' },
  { id: 'air', name: 'Air', icon: '💨', description: 'Discover air quality and atmospheric science', order: 13, totalLessons: 30, color: '#B0BEC5' },
  { id: 'soil', name: 'Soil', icon: '🏔️', description: 'Study soil types, erosion, and conservation', order: 14, totalLessons: 30, color: '#8D6E63' },
  { id: 'habitats', name: 'Habitats', icon: '🏡', description: 'Explore where plants and animals live', order: 15, totalLessons: 30, color: '#66BB6A' },
  { id: 'foodchain', name: 'Food Chain', icon: '🐛', description: 'Understand who eats what in nature', order: 16, totalLessons: 30, color: '#FF7043' },
  { id: 'birds', name: 'Birds', icon: '🦅', description: 'Discover birds, their species, and habitats', order: 17, totalLessons: 30, color: '#42A5F5' },
  { id: 'insects', name: 'Insects', icon: '🐝', description: 'Learn about bugs, bees, and butterflies', order: 18, totalLessons: 30, color: '#FFA726' },
  { id: 'solar', name: 'Solar Energy', icon: '☀️', description: 'Harness the power of the sun', order: 19, totalLessons: 30, color: '#FDD835' },
  { id: 'wind', name: 'Wind Energy', icon: '💨', description: 'Learn about wind power and turbines', order: 20, totalLessons: 30, color: '#81D4FA' },
  { id: 'hydro', name: 'Hydro Energy', icon: '🌊', description: 'Discover water power and dams', order: 21, totalLessons: 30, color: '#4FC3F7' },
  { id: 'plastic', name: 'Plastic Pollution', icon: '🧴', description: 'Understand plastic waste and solutions', order: 22, totalLessons: 30, color: '#EF5350' },
  { id: 'waste', name: 'Waste Management', icon: '🗑️', description: 'Learn proper waste disposal and sorting', order: 23, totalLessons: 30, color: '#78909C' },
  { id: 'composting', name: 'Composting', icon: '🌿', description: 'Turn waste into nutrient-rich soil', order: 24, totalLessons: 30, color: '#66BB6A' },
  { id: 'greentech', name: 'Green Technology', icon: '💡', description: 'Explore eco-friendly inventions', order: 25, totalLessons: 30, color: '#26A69A' },
  { id: 'protection', name: 'Environmental Protection', icon: '🛡️', description: 'Learn to protect our planet', order: 26, totalLessons: 30, color: '#EC407A' },
];
module.exports = categories;